# Quarkus development configuration
quarkus.profile=dev
quarkus.http.host=0.0.0.0
quarkus.http.port=8080

# MySQL configuration for local development
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/hotel_22
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file

# MongoDB configuration
quarkus.mongodb.connection-string=mongodb+srv://levanchinh13052005_db_user:ZnNNmXhZq98owuOC@cluster0.j9w8jmh.mongodb.net/?appName=Cluster0
quarkus.mongodb.database=hotel_22
